version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - 8000:8000

  chatbot-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=http://chromadb:8000